FROM docker.io/ubuntu:latest

RUN apt-get update -y && apt-get install -y curl systemd systemd-container direnv sudo git

# Install nix
RUN curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux \
  --extra-conf "sandbox = false" \
  --no-start-daemon \
  --no-confirm

# Setup evap user and group
RUN groupadd --gid 1001 evap && useradd --uid 1001 --gid 1001 --no-user-group --groups sudo -ms /bin/bash evap && echo evap:evap | chpasswd
USER evap
WORKDIR /evap
RUN echo 'cd /evap/' >> ~/.bashrc

# Setup direnv and nix-direnv
RUN echo 'eval "$(direnv hook bash)"' >> ~/.bashrc
RUN mkdir -p ~/.config/direnv/ && cat >> ~/.config/direnv/direnvrc <<EOF
if ! has nix_direnv_version || ! nix_direnv_version 3.0.6; then
  source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/3.0.6/direnvrc" "sha256-RYcUJaRMf8oF5LznDrlCXbkOQrywm0HDv1VjYGaJGdM="
fi
EOF
RUN cat > ~/.config/direnv/direnv.toml <<EOF
[whitelist]
prefix = [ "/evap" ]
EOF

# Automatically start database on boot
USER root
RUN mkdir -p /etc/systemd/system/ /evap-data && chown evap:evap /evap-data && cat > /etc/systemd/system/evap-services.service <<EOF
[Unit]
Description=EvaP Database Services

[Service]
User=evap
Type=simple
WorkingDirectory=/evap-data
ExecStart=/nix/var/nix/profiles/default/bin/nix run /evap#services -- up --tui=false
ExecStop=/nix/var/nix/profiles/default/bin/nix run /evap#services -- down

[Install]
WantedBy=default.target
EOF
RUN systemctl enable evap-services

CMD [ "/bin/systemd" ]
