# Generated by Django 1.9 on 2015-12-17 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_make_description_unique_per_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedocument',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_documents', to='evaluation.Course', verbose_name='Course'),
        ),
    ]
