# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0039_auto_20160104_1726'),
        ('grades', '0006_specify_on_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterGradeActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grades_active', to='evaluation.Semester')),
            ],
        ),
    ]
