# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 18:32
from __future__ import unicode_literals

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0007_semestergradedownloadactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedocument',
            name='description_de',
            field=models.CharField(default='description', max_length=255, verbose_name='description (german)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradedocument',
            name='description_en',
            field=models.CharField(default='description', max_length=255, verbose_name='description (english)'),
            preserve_default=False,
        ),
    ]
