# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 18:32
from __future__ import unicode_literals

from django.db import migrations, models


def save_description(apps, schema_editor):
    GradeDocument = apps.get_model("grades", "GradeDocument")
    gradeDocuments = GradeDocument.objects.all()
    for gradeDocument in gradeDocuments:
        gradeDocument.description_de = gradeDocument.description
        gradeDocument.description_en = gradeDocument.description
        gradeDocument.save()

def save_description_reverse(apps, schema):
    GradeDocument = apps.get_model("grades", "GradeDocument")
    gradeDocuments = GradeDocument.objects.all()
    for gradeDocument in gradeDocuments:
        gradeDocument.description = gradeDocument.description_de
        gradeDocument.save()


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_translate_description'),
    ]

    operations = [
        migrations.RunPython(save_description, reverse_code=save_description_reverse),
    ]
