# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0009_translate_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradedocument',
            unique_together=set([('course', 'description_de'), ('course', 'description_en')]),
        ),
        migrations.RemoveField(
            model_name='gradedocument',
            name='description',
        ),
    ]
