# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0009_fill_description_en'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradedocument',
            unique_together=set([('course', 'description_de'), ('course', 'description_en')]),
        ),
    ]
