# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0010_gradedocument_description_en_add_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedocument',
            name='last_modified_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_last_modified_user+', to=settings.AUTH_USER_MODEL),
        ),
    ]
