# Generated by Django 2.0.5 on 2018-06-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0011_auto_20160301_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestergradedownloadactivation',
            name='semester',
        ),
        migrations.DeleteModel(
            name='SemesterGradeDownloadActivation',
        ),
    ]
