# Generated by Django 5.2 on 2025-08-04 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluation", "0155_choices_constraints"),
        ("grades", "0017_remove_grade_documents_from_evaluations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="gradedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(("type__in", ["MID", "FIN"])), name="GradeDocument_type_choices"
            ),
        ),
    ]
