# Generated by Django 5.2 on 2026-01-12 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("evaluation", "0160_evaluation_staff_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="IgnoredEvaluation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cms_id",
                    models.CharField(max_length=255, unique=True, verbose_name="campus management system id"),
                ),
                ("name_de", models.CharField(blank=True, max_length=1024, verbose_name="name (german)")),
                ("name_en", models.CharField(blank=True, max_length=1024, verbose_name="name (english)")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ignored_evaluations",
                        to="evaluation.course",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name": "ignored evaluation",
                "verbose_name_plural": "ignored evaluations",
            },
        ),
    ]
