# Generated by Django 5.2 on 2026-01-19 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
        ("evaluation", "0160_evaluation_staff_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseLink",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cms_id", models.CharField(max_length=255, unique=True, verbose_name="campus management system id")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_links",
                        to="evaluation.course",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name": "course link",
                "verbose_name_plural": "course links",
            },
        ),
        migrations.CreateModel(
            name="EvaluationLink",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cms_id", models.CharField(max_length=255, unique=True, verbose_name="campus management system id")),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_links",
                        to="evaluation.evaluation",
                        verbose_name="evaluation",
                    ),
                ),
            ],
            options={
                "verbose_name": "evaluation link",
                "verbose_name_plural": "evaluation links",
            },
        ),
    ]
