# Generated by Django 5.2 on 2026-02-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0002_courselink_evaluationlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="courselink",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AddField(
            model_name="evaluationlink",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
    ]
