from datetime import timedelta
from fractions import Fraction
from pathlib import Path
from typing import Any

ACTIVATE_OPEN_ID_LOGIN: bool
ADMINS: list[tuple[str, str]]
CONTACT_EMAIL: str
DATADIR: Path
ENABLE_DEBUG_TOOLBAR: bool
EVALUATION_END_OFFSET_HOURS: int
EXAM_QUESTIONNAIRE_IDS: list[int]
GLOBAL_EVALUATION_PROGRESS_EXCLUDED_COURSE_TYPE_IDS: list[int]
GLOBAL_EVALUATION_PROGRESS_EXCLUDED_EVALUATION_IDS: list[int]
GLOBAL_EVALUATION_PROGRESS_INFO_TEXT: dict[str, str]
GLOBAL_EVALUATION_PROGRESS_REWARDS: list[tuple[Fraction, str]]
GRADE_REMINDER_EMAIL_RECIPIENTS: list[str]
IGNORE_PROGRAMS: set[str]
IMPORTER_COURSE_NAME_SIMILARITY_WARNING_THRESHOLD: float
IMPORTER_GRADED_NO: list[str]
IMPORTER_GRADED_YES: list[str]
IMPORTER_MAX_ENROLLMENTS: int
INSTITUTION_EMAIL_DOMAINS: list[str]
INSTITUTION_EMAIL_REPLACEMENTS: list[tuple[str, str]]
LEGAL_NOTICE_TEXT: str
MEDIA_ROOT: Path
MODULE: Path
NON_RESPONSIBLE_USERS: set[str]
OIDC_EMAIL_TRANSITIONS: dict[str, str]
PAGE_URL: str
PARTICIPATION_DELETION_AFTER_INACTIVE_TIME: timedelta
REPLY_TO_EMAIL: str
REWARD_POINTS: list[tuple[float, int]]
SEND_ALL_EMAILS_TO_ADMINS_IN_BCC: bool
SMALL_COURSE_SIZE: int
TEMPLATES: Any
VOTER_COUNT_NEEDED_FOR_PUBLISHING_RATING_RESULTS: int
