# Generated by Django 1.9 on 2015-12-17 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_django18warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardpointgranting',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reward_point_grantings', to='evaluation.Semester'),
        ),
        migrations.AlterField(
            model_name='rewardpointredemption',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_point_redemptions', to='rewards.RewardPointRedemptionEvent'),
        ),
    ]
