# Generated by Django 1.9.5 on 2016-05-08 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_specify_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardpointgranting',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_point_grantings', to='evaluation.Semester'),
        ),
    ]
