# Generated by Django 4.1.8 on 2023-05-22 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rewards", "0004_make_granting_semester_non_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewardpointredemption",
            name="value",
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name="value"),
        ),
        migrations.AlterField(
            model_name="rewardpointgranting",
            name="value",
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name="value"),
        ),
    ]
