# Generated by Django 5.0.4 on 2024-08-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0005_alter_rewardpoint_minvalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardpointredemptionevent",
            name="step",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Only multiples of this step can be redeemed.", verbose_name="redemption step"
            ),
        ),
    ]
