name: "Setup nodejs"
description: "Sets up nodejs for use in actions with caching"

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache: npm

    - name: Install Node dependencies
      run: npm ci
      shell: bash
