name: "Setup Python"
description: "Sets up Python for use in actions with caching and copy localsettings"

inputs:
  requirements-file:
    description: "name of the requirements file to install"
    required: false
    default: requirements-dev.txt

runs:
  using: "composite"
  steps:
    - name: Setup python
      id: python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Restore venv cache
      id: cache-virtualenv
      uses: actions/cache@v4
      with:
        path: .venv
        # hashFiles( 'requirements*.txt' ) because -dev.txt includes requirements.txt
        key: venv-${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{ hashFiles( 'requirements*.txt' ) }}-${{ inputs.requirements-file }}

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r "${{ inputs.requirements-file }}"
      shell: bash
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - name: Add localsettings
      run: cp evap/settings_test.py evap/localsettings.py
      shell: bash

    - name: Activate venv
      run: |
        source .venv/bin/activate
        echo "$PATH" >> "$GITHUB_PATH"
        echo PATH="$PATH" >> "$GITHUB_ENV"
        echo VIRTUAL_ENV="$VIRTUAL_ENV" >> "$GITHUB_ENV"
        echo PYTHONHOME="$PYTHONHOME" >> "$GITHUB_ENV"
      shell: bash
