name: "Setup Python"
description: "Sets up Python for use in actions with caching and copy localsettings"

inputs:
  install-dev-dependencies:
    description: "if disabled this will only install runtime dependencies"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Compute requirements files
      run: |
        cache_files="requirements.txt"
        requirements_file="requirements.txt"
        if [[ ${{ inputs.install-dev-dependencies }} == 'true' ]]; then
          cache_files="requirements*.txt"
          requirements_file="requirements-dev.txt"
        fi
        echo cache-files=$cache_files >> $GITHUB_ENV
        echo requirements-file=$requirements_file >> $GITHUB_ENV
      shell: bash

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Restore venv cache
      id: cache-virtualenv
      uses: actions/cache4@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles( env.cache-files ) }}

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r "${{ env.requirements-file }}"
      shell: bash
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - name: Add localsettings
      run: cp evap/settings_test.py evap/localsettings.py
      shell: bash

    - name: Activate venv
      run: |
        source .venv/bin/activate
        echo $PATH >> $GITHUB_PATH
        echo PATH=$PATH >> $GITHUB_ENV
        echo VIRTUAL_ENV=$VIRTUAL_ENV >> $GITHUB_ENV
        echo PYTHONHOME=$PYTHONHOME >> $GITHUB_ENV
      shell: bash
