name: "Setup Python"
description: "Sets up Python for use in actions with caching and copy localsettings"

inputs:
  install-dev-requirements:
    description: "if disabled this will only install runtime dependencies"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Deduce requirements file
      env:
        install_dev: ${{ inputs.install-dev-requirements }}
      run: |
        if [[ $install_dev == 'true' ]]; then
          REQUIREMENTS_TXT='requirements-dev.txt'
        else REQUIREMENTS_TXT='requirements.txt'
        
        echo "requirements_txt=$REQUIREMENTS_TXT" >> $GITHUB_ENV
      shell: bash

    - name: Restore venv cache
      uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv

    - name: Restore pip download cache
      uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      with:
        requirement_files: ${{ env.requirements_txt }}

    - name: Install dependencies
      env:
        requirements_txt: ${{ env.requirements_txt }}
      run: pip install -r $requirements_txt
      shell: bash
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - name: Add localsettings
      run: cp evap/settings_test.py evap/localsettings.py
      shell: bash
