name: "Setup Python"
description: "Sets up Python for use in actions with caching and copy localsettings"

inputs:
  requirements-file:
    description: "if disabled this will only install runtime dependencies"
    required: false
    default: requirements-dev.txt

runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Restore venv cache
      uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: ${{ inputs.requirements-file }}

    - name: Restore pip download cache
      uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      with:
        requirement_files: ${{ inputs.requirements-file }}

    - name: Install dependencies
      env:
        requirements_txt: ${{ inputs.requirements-file }}
      run: pip install -r $requirements_txt
      shell: bash
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - name: Add localsettings
      run: cp evap/settings_test.py evap/localsettings.py
      shell: bash
